<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Bokka" failures="1" tests="2" name="tutorialsNinjaTests.GiftCertificateTest" time="12.932" errors="0" timestamp="2023-02-06T21:04:48 CET" skipped="0">
  <testcase classname="tutorialsNinjaTests.GiftCertificateTest" name="giftCertificateWithOutNonRefundableTerms" time="6.295"/>
  <system-out/>
  <testcase classname="tutorialsNinjaTests.GiftCertificateTest" name="giftCertificateWithRefundableTerms" time="6.637">
    <failure message="The following asserts failed:
	expected [$1.00 Gift Certificate for ben] but found [Image Product Name Model Quantity Unit Price Total
HTC Touch HD ***
Reward Points: 400 Product 1
$100.00 $100.00
iPhone *** product 11
$101.00 $8,888.00
Samsung Galaxy Tab 10.1 ***
Reward Points: 1000 SAM1
$199.99 $199.99
$1.00 Gift Certificate for ben
$1.00 $1.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [$1.00 Gift Certificate for ben] but found [Image Product Name Model Quantity Unit Price Total
HTC Touch HD ***
Reward Points: 400 Product 1
$100.00 $100.00
iPhone *** product 11
$101.00 $8,888.00
Samsung Galaxy Tab 10.1 ***
Reward Points: 1000 SAM1
$199.99 $199.99
$1.00 Gift Certificate for ben
$1.00 $1.00]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at tutorialsNinjaTests.GiftCertificateTest.giftCertificateWithRefundableTerms(GiftCertificateTest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- giftCertificateWithRefundableTerms -->
  <system-out/>
</testsuite> <!-- tutorialsNinjaTests.GiftCertificateTest -->
